# coding: utf-8

"""
    Esper SDK

    Python client library for Esper Manage APIs. You can find out more about Esper at [https://shoonya.io](https://shoonya.io).  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: developer@esper.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import esperclient
from esperclient.api.device_api import DeviceApi
from esperclient.rest import ApiException


class TestDeviceApi(unittest.TestCase):
    """DeviceApi unit test stubs"""

    def setUp(self):
        self.api = esperclient.api.device_api.DeviceApi()

    def tearDown(self):
        pass

    def test_get_all_devices(self):
        """Test case for get_all_devices

        Fetch all devices in an enterprise
        """
        pass

    def test_get_device_by_id(self):
        """Test case for get_device_by_id

        Fetch device details by ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
