# coding: utf-8

"""
    Esper SDK

    This is a read only Esper SDK.  You can find out more about Esper at [https://shoonya.io](https://shoonya.io).  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: developer@shoonya.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import esper
from api.commands_api import CommandsApi  # noqa: E501
from esper.rest import ApiException


class TestCommandsApi(unittest.TestCase):
    """CommandsApi unit test stubs"""

    def setUp(self):
        self.api = api.commands_api.CommandsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_run_command(self):
        """Test case for run_command

        Run commands on device  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
