# coding: utf-8

"""
    Esper SDK

    This is a read only Esper SDK.  You can find out more about Esper at [https://shoonya.io](https://shoonya.io).  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: developer@shoonya.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import esper
from api.device_api import DeviceApi  # noqa: E501
from esper.rest import ApiException


class TestDeviceApi(unittest.TestCase):
    """DeviceApi unit test stubs"""

    def setUp(self):
        self.api = api.device_api.DeviceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_devices(self):
        """Test case for get_all_devices

        Find devices in an enterprise  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
