# coding: utf-8

"""
    Esper SDK

    This is a read only Esper SDK.  You can find out more about Esper at [https://shoonya.io](https://shoonya.io).  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: developer@shoonya.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import esper
from models.device_command_request import DeviceCommandRequest  # noqa: E501
from esper.rest import ApiException


class TestDeviceCommandRequest(unittest.TestCase):
    """DeviceCommandRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceCommandRequest(self):
        """Test DeviceCommandRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = esper.models.device_command_request.DeviceCommandRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
