# coding: utf-8

"""
    Esper SDK

    Python client library for Esper Manage APIs. You can find out more about Esper at [https://shoonya.io](https://shoonya.io).  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: developer@esper.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "esperclient"
VERSION = "0.0.1"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi>=2017.4.17",
    "python-dateutil>=2.1",
    "six>=1.10",
    "urllib3>=1.23"
]
    

setup(
    name=NAME,
    version=VERSION,
    description="Esper SDK",
    author_email="developer@esper.io",
    url="",
    keywords=["Swagger", "Esper SDK"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    Esper Manage python SDK

    Python client library for Esper Manage APIs. You can find out more about Esper at https://shoonya.io.

    - API version: 1.0.0
    - Package version: 0.0.1

    For usage instructions and API documentation please visit: https://github.com/esper-io/esper-client-py

    """,
    long_description_content_type='text/markdown'
)
