# coding: utf-8

"""
Esper APIs

OpenAPI spec version: 1.0.0
Contact: developer@esper.io
---------------------------------------------------------

Copyright 2019 Shoonya Enterprises Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""



import pprint
import re

import six


class DeviceCommandEnum(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    REBOOT = "REBOOT"
    LOCK = "LOCK"
    INSTALL = "INSTALL"
    UPDATE_HEARTBEAT = "UPDATE_HEARTBEAT"
    WIPE = "WIPE"
    SET_WIFI_STATE = "SET_WIFI_STATE"
    SET_BLUETOOTH_STATE = "SET_BLUETOOTH_STATE"
    SET_ROTATION_STATE = "SET_ROTATION_STATE"
    SET_GPS_STATE = "SET_GPS_STATE"
    SET_BRIGHTNESS_SCALE = "SET_BRIGHTNESS_SCALE"
    SET_STREAM_VOLUME = "SET_STREAM_VOLUME"
    SET_SCREEN_OFF_TIMEOUT = "SET_SCREEN_OFF_TIMEOUT"
    UNINSTALL = "UNINSTALL"
    ADD_TO_WHITELIST = "ADD_TO_WHITELIST"
    CLEAR_APP_DATA = "CLEAR_APP_DATA"

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
    }

    attribute_map = {
    }

    def __init__(self):
        """DeviceCommandEnum - a model defined in Swagger"""
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeviceCommandEnum, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeviceCommandEnum):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
